version: 1.0.{build}
os:
  - Visual Studio 2017
clone_depth: 1
configuration:
  - Release
platform:
  - Win32
environment:
  matrix:
    - TOOLCHAIN_VERSION: 14.0
    - TOOLCHAIN_VERSION: 12.0
before_build:
    # This is the recommended way to choose the toolchain version, according to
    # Appveyor's documentation.
    - SET PATH=C:\Program Files (x86)\MSBuild\%TOOLCHAIN_VERSION%\Bin;%PATH%
build:
  project: ring.sln
  parallel: true
  verbosity: normal
test_script:
  - go run util/all_tests.go -build-dir=build/%Platform%-%Configuration%/test/ring